### ISSUE TITLE
css and javascript issues

### ISSUE THREAD

**Issue by jamesalbert** [murlokswarm/app#223]
possibly related to #21 

Trying to include font-awesome stylesheets, using `<link href="...">` worked fine, but having the css in `resources/css` the icons are rendering as squares.

Only `<script>...</script>`'s seem to be working. Both files in `resources/js` and `<script src="https...">` don't seem to work.

If there is a javascript exception thrown, I don't hear about it in the logs.

My questions are:
  - is this expected behavior, or have these features been known to work? In that case I can provide more info.
  - are there any plans for a dev console to inspect html / debug js? That would be glorious.

**Comment by maxence-charriere** [comment]
can you provide the snippet where you use ```<link href="...">``` ??

**Comment by jamesalbert** [comment]
@maxence-charriere that's some record response time 😄 

Yeah, so this works for me:
```
<div class="SelectionMenu">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    ...
```

**Comment by jamesalbert** [comment]
closed by accident

**Comment by maxence-charriere** [comment]
so what is the snippet where it does not work ?

**Comment by jamesalbert** [comment]
so that's just a template I'm returning in my component's Render()

While that link imports the css just fine, having the css in `resources/css`, the icons are just squares

**Comment by maxence-charriere** [comment]
I don't understand what you mean, can you give more details ?
if you put your font in the `resource/css` folder, how do you include it in your component ?

**Comment by maxence-charriere** [comment]
For the javascript logs, I would say just to launch it with `goapp web run -chrome` and use chrome debugger directly.

**Comment by jamesalbert** [comment]
I'm not including it in particular so according to the docs, all the css gets loaded.

css in `resources/css` works fine in general. It's just font-awesome in particular doesn't seem to work when loaded from `resources/css`. For example, when Render() returns:

```
<div class="SelectionMenu">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <a class="fa fa-github"></a>
    ....
```
^ This will show a github icon.

However, if I have font-awesome.css in `resources/css` with Render() returning:

```
<div class="SelectionMenu">
    <a class="fa fa-github"></a>
    ....
```

A square is rendered. To prove that `resources/css/font-awesome.css` is loaded, I removed it, and the squares went away.

**Comment by jamesalbert** [comment]
`goapp web` isn't an option for me. It fails with `github.com/veandco/go-sdl2/sdl: importing "C" is not supported by GopherJS`.

I think it's because I'm using gobot

**Comment by maxence-charriere** [comment]
is it because `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css` refer to external resources that are relative to the remote location ?

**Comment by maxence-charriere** [comment]
look like its the case:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
